version: '3.8'

services:
  server1:
    build: ./server1
    ports:
      - "8081:8081"

  server2:
    build: ./server2
    ports:
      - "8082:8082"

  server3:
    build: ./server3
    ports:
      - "8083:8083"

  proxy:
    build: .
    ports:
      - "8087:8087"
    depends_on:
      - server1
      - server2
      - server3
